version: '3.8'

services:
  node-app:
    build: .
    image: node-app-image
    ports:
      - 8080:8000
    environment:
      - PORT=8000
  mongo:
    image: mongo:6
    restart: always
    command: --wiredTigerCacheSizeGB 1.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
#     volumes:
#       - mongo_db:/data/db
# volumes:
#   mongo_db:
